### ISSUE TITLE
Heal when knocked out

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#4]
I went AFK for a second and some thugs pulled me out of my squad car and beat me down. I got to the comp to see me in the red and then heal while down until I had full health. When he was kicking me during the healing process, it didn't negatively effect the regeneration process. If anything, the health should stay at whatever it was when you got knocked out, until back up on your feet.

**Comment by HIsShadowONE** [comment]
this is intentional as NPCs dont see the knocked out state and could just kill you while you regen stamina to get back up. just a compromise we have to live with to get the benefits of the knock out function to prevent instant coma state when taking mere fists or getting hit on the ground. however if you are low health and cant heal (dont have items to do so) you will end up in coma as seems proper rp to real life.
(hope this explanation makes sense)
