### ISSUE TITLE
F50 Crash

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#6]
Same issue as Tesla

**Comment by TheTrueMac** [comment]
SKYLINE TOO    D:

**Comment by HIsShadowONE** [comment]
I have fixed the add on cars that dont require handling changes , the special addon cars will be re-added once i change each of them individually to use a standard in game cars handling to avoid the suspension issues they cause with NPC vehicles and stop crashes , for now this issue is solved , will leave opened till task is completed.
